name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  
defaults:
  run:
    working-directory: rust

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      uses: actions-rs/clippy-check@v1.0.7
      with:
        toolchain: nightly 

