name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  
defaults:
  run:
    working-directory: rust

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Apt-get update
      run: sudo apt-get update
      
    - name: Install dependencies
      run: DEBIAN_FRONTEND=noninteractive sudo apt-get install -y clang libclang-dev libopencv-contrib4.2 libopencv-dev curl 
      
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            components: clippy
            override: true
      
    - name: Build
      run: cargo build --verbose
      
    - name: Clippy
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        toolchain: nightly 
        args: --all-features --manifest-path rust/Cargo.toml
        # see https://github.com/actions-rs/clippy-check/issues/28
        
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.12
      with:
        folder-path: .
        config-file: .github/workflows/markdown-link-check-config.json

